src/index.spec.ts, src/index.ts
The {src;dest;} multi-level globs don't work the same as the root level globs, but they should. This fixes that.
=> Fix src;dest; globs

.vscode/launch.json, package-lock.json, readme.md, rokudeploy.json, src/Errors.ts, src/RokuDeploy.spec.ts, src/RokuDeploy.ts, src/device.spec.ts, src/index.ts, tslint.json
Add rekeying capability as requested in #16, Start moving to named errors instead of checking if error messages match, quit calling assert.fail within a try block to avoid possible weird behavior, add doGetRequest, checkRequest, mockDoPostRequest and mockDoGetRequest to remove a lot of boiler plate
=> Add rekeying capability as requested in #16

src/RokuDeploy.spec.ts, src/RokuDeploy.ts, testProject/manifest
bs_const uses equal signs in the right hand side which ini then adds quotes around the whole thing. It doesn't seem like a fix will be available soon (https://github.com/npm/ini/issues/57) so we remove it before stringifying and add it back in afterwards to get around this.
=> Manifest with bs_const weren't being handled correctly. This fixes it

src/RokuDeploy.spec.ts, src/RokuDeploy.ts
Ignore 202 response codes on home key presses since this should be a fire and forget call anyways and causes issues that really aren't issues when we receive a 202 response code.
=> Ignore 202 response codes on home key presses

package-lock.json, package.json, src/RokuDeploy.spec.ts, src/RokuDeploy.ts
Fix issues with latest release that crash for windows slashes.
Add missing `chalk` dependency.
Fixes https://github.com/rokucommunity/vscode-brightscript-language/issues/315
Fixes https://github.com/rokucommunity/vscode-brightscript-language/issues/314
=> Fix critical issues

package-lock.json, src/RokuDeploy.spec.ts, src/RokuDeploy.ts
addresses: https://github.com/rokucommunity/roku-deploy/issues/64
=> wraps call to delete installed cahnnel in try catch, so that deployments continue

src/RokuDeploy.ts
v3.5.0 introduced a bug where we closed the read stream before sending the request to the server. This fixes that problem.
=> fix order-of-ops issue with rekeyDevice call

src/RokuDeploy.spec.ts, src/RokuDeploy.ts
Importing roku-deploy into a typescript project sometimes shows type errors because of a missing `@types/request` package. This is a devDependency, so it shouldn't clutter the production dependencies. 
Also, we're only storing `request` on `RokuDeploy` to help with unit testing. However, we don't actually need to do that, since we  can already stub/mock the `request` object as long as it's imported as `import * as request from 'request'`. 
This _might_ be a breaking change if any projects were utilizing the `rokuDeploy.request` property, but realistically that should have been a private property anyway, and there's an easy fix (import `request` in the host project...).
=> Remove `request` prop from `RokuDeploy` class

package-lock.json, package.json, src/RokuDeploy.spec.ts, src/RokuDeploy.ts, src/util.spec.ts, src/util.ts
Fixes several performance issues related to globbing for files. 
- run all glob lookups in parallel instead of sequentially
- negative globs no longer run a glob and then remove those entries from the overall result. Instead, the negative globs are used to filter previous matches. This is significantly faster.
- switch to a faster glob library. We currently use node-glob. Based on my preliminary tests, fdir is the fastest. However, there's a bug in that library right now related to symlinks, so for now we will use `fast-glob`. (EDIT: fdir has a few other design differences that prevent us from switching. fast-glob is plenty fast). 
To benchmark this, I ran the following roku-deploy command against a folder with >64,000 files:
```typescript
await rokuDeploy.getFilePaths([
'**/*', …
```
=> Performance improvements

README.md, src/RokuDeploy.spec.ts, src/RokuDeploy.ts, src/RokuDeployOptions.ts
Just wanted to add an option to not delete the previously installed channel upon publishing as sometimes it proves to be unneccesary and delete local storage files associated with the channel and can slow down iteration time.
=> Add deleteInstalledChannel option

src/RokuDeploy.spec.ts, src/RokuDeploy.ts
Adds a files array parameter to `zipFolder` to allow files to be included/excluded from the zip. This is mostly useful for vscode-brightscript-language to exclude files like sourcemaps from getting uploaded to the device (and save lots of performace doing so).
=> Allow filtering files during `zipFolder`

src/Errors.ts, src/RokuDeploy.spec.ts, src/RokuDeploy.ts, src/index.ts
- Detect compile errors on the `replace` call, which prevents retrying with `install` if failed.
- Attach the roku messages to the `CompileError` class.
- Export the error classes
=> Better compile error handling

src/RokuDeploy.spec.ts, src/RokuDeploy.ts
Fixes a critical backwards compatibility issue that was incorrectly deleting `stagingFolderPath` and `retainStagingFolder` after the transition to `stagingDir` and `retainStagingDir` in #99
=> Sync retainStagingFolder, stagingFolderPath with options.

package-lock.json, package.json
- Remove `minimatch` dependency (no longer used)
- Add `picomatch` dependency (matching version spec for mocha)
When you install `roku-deploy` in pnpm workspaces in strict mode, you'll get errors at runtime because the source code uses `picomatch`, but that package isn't declared in the package json (it is transitively installed and hoisted by npm).
Here's my `npm why` output (should all bubble up to one install):
```console
picomatch@2.3.0
node_modules/picomatch
picomatch@"^2.2.1" from the root project
picomatch@"^2.0.4" from anymatch@3.1.2
node_modules/anymatch
anymatch@"~3.1.2" from chokidar@3.5.3
node_modules/chokidar
chokidar@"3.5.3" from mocha@9.2.2
node_modules/mocha
dev mocha@"^9.1.3" from the root project
picomatch@"^2.2.3" from micromatch@4.0.4
node_modules/micromatch …
```
=> Replace minimatch with picomatch

src/RokuDeploy.ts
'Request' module post requests fail with Nodejs v19 and up. To make it compatible with newer versions of node simply pass the following config values to the request apis to overcome socket error: agentOptions: { 'keepAlive': false }
=> TBD-67: roku-deploy: fix nodejs 19 bug

.github/workflows/build.yml, src/RokuDeploy.spec.ts
Fixes a bug when running the roku-deploy unit test suite that accidentally overwrites the signingPackage.pkg file, by using tempDir instead in the tests.
=> Fix bug that overwrites signing pkg during tests

src/RokuDeploy.spec.ts, src/RokuDeploy.ts
Found that it is possible to get errors in a json object within the response. This adds checks for that.
=> Added some more message grabbing logic

src/RokuDeploy.ts
Adds better jsdoc descriptions for the `GetDeviceInfoOptions` interface properties.
=> Add better device-info jsdoc block

src/RokuDeploy.spec.ts, src/RokuDeploy.ts
Improves the "wrong password" error message.
=> Update wrong host password error message

src/RokuDeploy.spec.ts, src/RokuDeploy.ts
We occasionally see the convertToSquashfs request fail. It seems determined by the size of the zip and the length of the file name. The Roku responds with half of the response body and roku-deploy cannot handle the bad data.
The squashfs conversion looks like it successfully created, the error is in the response.
The work around is to make a second request to squashfs when we see the 'HPE_INVALID_CONSTANT' error. If that response includes 'fileType': 'squashfs' then we return the result saying it succeeded.
=> Retry the convertToSquahsfs request given the HPE_INVALID_CONSTANT error

package-lock.json, src/RokuDeploy.spec.ts, src/RokuDeploy.ts, src/RokuDeployOptions.ts
Adds ability to override package upload properties like `route` and `formData`
=> Support overriding various package upload form data

src/RokuDeploy.spec.ts, src/RokuDeploy.ts
fixes #175 
the current implementation tries to parse a package's remote path from  `<a .../>` on `/plugin_package`. that link is not always correct ( for example if you device has a sdcard installed )
`/plugin_package` page response always have `var params = JSON.parse('......')` line. And the actual link ( when you opens the page in the browser ) built from the following js 
```javascript
var pkgs = params.packages.filter(p => p.pkgPath !== "");
var hasPkgApp = pkgs.length > 0;
{
var pkgDiv = document.createElement('div');
if (hasPkgApp) {
var package = pkgs[0];
var pkgPath = package.pkgPath;
var pkgName = package.pkgPath.substr(package.pkgPath.lastIndexOf('/') + 1);
var size = package.size;
pkgDiv.innerHTML = `<label>Currently Packaged Application:</label>
<div>
<font face="Courier"> …
```
=> fixes #175 - updated regex to find a signed package on `/plugin_package` page

package.json, src/Errors.ts, src/RokuDeploy.spec.ts, src/RokuDeploy.ts
Improves upon #180 . Apparently the device actually returns status code `200` instead of `577`. `577` is some other type of error, we should handle that separately.
This now checks for `200` responses to see if the exact text `'Failed to check for software update'` is found. If so, that's when we throw the `UpdateCheckRequiredError` error.
=> Fix issues with detecting "check for updates required"

src/RokuDeploy.spec.ts, src/RokuDeploy.ts
Improves upon https://github.com/rokucommunity/roku-deploy/pull/180 by handling when the initial "Replace" call fails. Some devices return 577 or "update check required" 200 response on the `replace` request, but then timeout on the `install` request. 
This fixes that by detecting that issue in the `Replace` request and then failing sooner rather than attempting the `Install` next.
=> fixed an issue with 577 error codes

README.md, src/RokuDeploy.spec.ts, src/RokuDeploy.ts
This PR accomplishes the following:
- include the User-Agent for every GET and POST request
- replace the [non-compliant user agent](https://github.com/rokucommunity/roku-deploy/blob/26e555d76baa757dfa1ce61beb86dbf73862cb1e/src/RokuDeploy.ts#L1089) with a compliant one. 
The User-Agent header is now the name of the tool (`roku-deploy/`) followed by the full version of the tool. If you're using a prerelease or temporary testing version of roku-deploy, that information will also be included. Here are some examples:
```
User-Agent: roku-deploy/3.12.6
User-Agent: roku-deploy/4.0.0-alpha.12
User-Agent: roku-deploy/3.12.7-some-branch-name-123.3958293294854
```
If for some strange reason we were unable to find the version number, then the `User-Agent` will be:
```
User-Agent: roku-deploy/unknown …
```
=> Add standards-compliant User-Agent header
